// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nedo/TicketSaas/service/payment/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefundRepository creates a new instance of MockRefundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefundRepository {
	mock := &MockRefundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefundRepository is an autogenerated mock type for the RefundRepository type
type MockRefundRepository struct {
	mock.Mock
}

type MockRefundRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefundRepository) EXPECT() *MockRefundRepository_Expecter {
	return &MockRefundRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRefundRepository
func (_mock *MockRefundRepository) Create(ctx context.Context, refund *domain.RefundRequest) error {
	ret := _mock.Called(ctx, refund)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RefundRequest) error); ok {
		r0 = returnFunc(ctx, refund)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefundRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefundRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - refund *domain.RefundRequest
func (_e *MockRefundRepository_Expecter) Create(ctx any, refund any) *MockRefundRepository_Create_Call {
	return &MockRefundRepository_Create_Call{Call: _e.mock.On("Create", ctx, refund)}
}

func (_c *MockRefundRepository_Create_Call) Run(run func(ctx context.Context, refund *domain.RefundRequest)) *MockRefundRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RefundRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.RefundRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefundRepository_Create_Call) Return(err error) *MockRefundRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefundRepository_Create_Call) RunAndReturn(run func(ctx context.Context, refund *domain.RefundRequest) error) *MockRefundRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
