// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentClient creates a new instance of MockPaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentClient {
	mock := &MockPaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentClient is an autogenerated mock type for the PaymentClient type
type MockPaymentClient struct {
	mock.Mock
}

type MockPaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentClient) EXPECT() *MockPaymentClient_Expecter {
	return &MockPaymentClient_Expecter{mock: &_m.Mock}
}

// InitiateTxnForBooking provides a mock function for the type MockPaymentClient
func (_mock *MockPaymentClient) InitiateTxnForBooking(ctx context.Context, bookingID string, eventID string, userID string, email string, amountRupiah int, expiresAt time.Time) error {
	ret := _mock.Called(ctx, bookingID, eventID, userID, email, amountRupiah, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for InitiateTxnForBooking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, time.Time) error); ok {
		r0 = returnFunc(ctx, bookingID, eventID, userID, email, amountRupiah, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentClient_InitiateTxnForBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateTxnForBooking'
type MockPaymentClient_InitiateTxnForBooking_Call struct {
	*mock.Call
}

// InitiateTxnForBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
//   - eventID string
//   - userID string
//   - email string
//   - amountRupiah int
//   - expiresAt time.Time
func (_e *MockPaymentClient_Expecter) InitiateTxnForBooking(ctx any, bookingID any, eventID any, userID any, email any, amountRupiah any, expiresAt any) *MockPaymentClient_InitiateTxnForBooking_Call {
	return &MockPaymentClient_InitiateTxnForBooking_Call{Call: _e.mock.On("InitiateTxnForBooking", ctx, bookingID, eventID, userID, email, amountRupiah, expiresAt)}
}

func (_c *MockPaymentClient_InitiateTxnForBooking_Call) Run(run func(ctx context.Context, bookingID string, eventID string, userID string, email string, amountRupiah int, expiresAt time.Time)) *MockPaymentClient_InitiateTxnForBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 time.Time
		if args[6] != nil {
			arg6 = args[6].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockPaymentClient_InitiateTxnForBooking_Call) Return(err error) *MockPaymentClient_InitiateTxnForBooking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentClient_InitiateTxnForBooking_Call) RunAndReturn(run func(ctx context.Context, bookingID string, eventID string, userID string, email string, amountRupiah int, expiresAt time.Time) error) *MockPaymentClient_InitiateTxnForBooking_Call {
	_c.Call.Return(run)
	return _c
}
