// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nedo/TicketSaas/internal/inventory/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventConsumer creates a new instance of MockEventConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventConsumer {
	mock := &MockEventConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventConsumer is an autogenerated mock type for the EventConsumer type
type MockEventConsumer struct {
	mock.Mock
}

type MockEventConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventConsumer) EXPECT() *MockEventConsumer_Expecter {
	return &MockEventConsumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockEventConsumer
func (_mock *MockEventConsumer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventConsumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventConsumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEventConsumer_Expecter) Close() *MockEventConsumer_Close_Call {
	return &MockEventConsumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEventConsumer_Close_Call) Run(run func()) *MockEventConsumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventConsumer_Close_Call) Return(err error) *MockEventConsumer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventConsumer_Close_Call) RunAndReturn(run func() error) *MockEventConsumer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// OnEventApproved provides a mock function for the type MockEventConsumer
func (_mock *MockEventConsumer) OnEventApproved(ctx context.Context, fn func(ctx context.Context, eventID string, ticketTypes []domain.TicketTypeInfo) error) {
	_mock.Called(ctx, fn)
	return
}

// MockEventConsumer_OnEventApproved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnEventApproved'
type MockEventConsumer_OnEventApproved_Call struct {
	*mock.Call
}

// OnEventApproved is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context, eventID string, ticketTypes []domain.TicketTypeInfo) error
func (_e *MockEventConsumer_Expecter) OnEventApproved(ctx any, fn any) *MockEventConsumer_OnEventApproved_Call {
	return &MockEventConsumer_OnEventApproved_Call{Call: _e.mock.On("OnEventApproved", ctx, fn)}
}

func (_c *MockEventConsumer_OnEventApproved_Call) Run(run func(ctx context.Context, fn func(ctx context.Context, eventID string, ticketTypes []domain.TicketTypeInfo) error)) *MockEventConsumer_OnEventApproved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, eventID string, ticketTypes []domain.TicketTypeInfo) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, eventID string, ticketTypes []domain.TicketTypeInfo) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventConsumer_OnEventApproved_Call) Return() *MockEventConsumer_OnEventApproved_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventConsumer_OnEventApproved_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context, eventID string, ticketTypes []domain.TicketTypeInfo) error)) *MockEventConsumer_OnEventApproved_Call {
	_c.Run(run)
	return _c
}

// OnEventCancelled provides a mock function for the type MockEventConsumer
func (_mock *MockEventConsumer) OnEventCancelled(ctx context.Context, fn func(ctx context.Context, eventID string) error) {
	_mock.Called(ctx, fn)
	return
}

// MockEventConsumer_OnEventCancelled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnEventCancelled'
type MockEventConsumer_OnEventCancelled_Call struct {
	*mock.Call
}

// OnEventCancelled is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context, eventID string) error
func (_e *MockEventConsumer_Expecter) OnEventCancelled(ctx any, fn any) *MockEventConsumer_OnEventCancelled_Call {
	return &MockEventConsumer_OnEventCancelled_Call{Call: _e.mock.On("OnEventCancelled", ctx, fn)}
}

func (_c *MockEventConsumer_OnEventCancelled_Call) Run(run func(ctx context.Context, fn func(ctx context.Context, eventID string) error)) *MockEventConsumer_OnEventCancelled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, eventID string) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, eventID string) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventConsumer_OnEventCancelled_Call) Return() *MockEventConsumer_OnEventCancelled_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventConsumer_OnEventCancelled_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context, eventID string) error)) *MockEventConsumer_OnEventCancelled_Call {
	_c.Run(run)
	return _c
}

// OnPaymentCompleted provides a mock function for the type MockEventConsumer
func (_mock *MockEventConsumer) OnPaymentCompleted(ctx context.Context, fn func(ctx context.Context, bookingID string, transactionID string) error) {
	_mock.Called(ctx, fn)
	return
}

// MockEventConsumer_OnPaymentCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPaymentCompleted'
type MockEventConsumer_OnPaymentCompleted_Call struct {
	*mock.Call
}

// OnPaymentCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context, bookingID string, transactionID string) error
func (_e *MockEventConsumer_Expecter) OnPaymentCompleted(ctx any, fn any) *MockEventConsumer_OnPaymentCompleted_Call {
	return &MockEventConsumer_OnPaymentCompleted_Call{Call: _e.mock.On("OnPaymentCompleted", ctx, fn)}
}

func (_c *MockEventConsumer_OnPaymentCompleted_Call) Run(run func(ctx context.Context, fn func(ctx context.Context, bookingID string, transactionID string) error)) *MockEventConsumer_OnPaymentCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, bookingID string, transactionID string) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, bookingID string, transactionID string) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventConsumer_OnPaymentCompleted_Call) Return() *MockEventConsumer_OnPaymentCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventConsumer_OnPaymentCompleted_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context, bookingID string, transactionID string) error)) *MockEventConsumer_OnPaymentCompleted_Call {
	_c.Run(run)
	return _c
}

// OnPaymentFailed provides a mock function for the type MockEventConsumer
func (_mock *MockEventConsumer) OnPaymentFailed(ctx context.Context, fn func(ctx context.Context, bookingID string) error) {
	_mock.Called(ctx, fn)
	return
}

// MockEventConsumer_OnPaymentFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPaymentFailed'
type MockEventConsumer_OnPaymentFailed_Call struct {
	*mock.Call
}

// OnPaymentFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context, bookingID string) error
func (_e *MockEventConsumer_Expecter) OnPaymentFailed(ctx any, fn any) *MockEventConsumer_OnPaymentFailed_Call {
	return &MockEventConsumer_OnPaymentFailed_Call{Call: _e.mock.On("OnPaymentFailed", ctx, fn)}
}

func (_c *MockEventConsumer_OnPaymentFailed_Call) Run(run func(ctx context.Context, fn func(ctx context.Context, bookingID string) error)) *MockEventConsumer_OnPaymentFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, bookingID string) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, bookingID string) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventConsumer_OnPaymentFailed_Call) Return() *MockEventConsumer_OnPaymentFailed_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventConsumer_OnPaymentFailed_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context, bookingID string) error)) *MockEventConsumer_OnPaymentFailed_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockEventConsumer
func (_mock *MockEventConsumer) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventConsumer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockEventConsumer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventConsumer_Expecter) Start(ctx any) *MockEventConsumer_Start_Call {
	return &MockEventConsumer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockEventConsumer_Start_Call) Run(run func(ctx context.Context)) *MockEventConsumer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventConsumer_Start_Call) Return(err error) *MockEventConsumer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventConsumer_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockEventConsumer_Start_Call {
	_c.Call.Return(run)
	return _c
}
