// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSeatCounter creates a new instance of MockSeatCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeatCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeatCounter {
	mock := &MockSeatCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSeatCounter is an autogenerated mock type for the SeatCounter type
type MockSeatCounter struct {
	mock.Mock
}

type MockSeatCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeatCounter) EXPECT() *MockSeatCounter_Expecter {
	return &MockSeatCounter_Expecter{mock: &_m.Mock}
}

// Available provides a mock function for the type MockSeatCounter
func (_mock *MockSeatCounter) Available(ctx context.Context, eventID string, ticketTypeID string) (int, error) {
	ret := _mock.Called(ctx, eventID, ticketTypeID)

	if len(ret) == 0 {
		panic("no return value specified for Available")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return returnFunc(ctx, eventID, ticketTypeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = returnFunc(ctx, eventID, ticketTypeID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, eventID, ticketTypeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeatCounter_Available_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Available'
type MockSeatCounter_Available_Call struct {
	*mock.Call
}

// Available is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - ticketTypeID string
func (_e *MockSeatCounter_Expecter) Available(ctx any, eventID any, ticketTypeID any) *MockSeatCounter_Available_Call {
	return &MockSeatCounter_Available_Call{Call: _e.mock.On("Available", ctx, eventID, ticketTypeID)}
}

func (_c *MockSeatCounter_Available_Call) Run(run func(ctx context.Context, eventID string, ticketTypeID string)) *MockSeatCounter_Available_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSeatCounter_Available_Call) Return(n int, err error) *MockSeatCounter_Available_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSeatCounter_Available_Call) RunAndReturn(run func(ctx context.Context, eventID string, ticketTypeID string) (int, error)) *MockSeatCounter_Available_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockSeatCounter
func (_mock *MockSeatCounter) Init(ctx context.Context, eventID string, ticketTypeID string, total int) error {
	ret := _mock.Called(ctx, eventID, ticketTypeID, total)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, eventID, ticketTypeID, total)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeatCounter_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockSeatCounter_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - ticketTypeID string
//   - total int
func (_e *MockSeatCounter_Expecter) Init(ctx any, eventID any, ticketTypeID any, total any) *MockSeatCounter_Init_Call {
	return &MockSeatCounter_Init_Call{Call: _e.mock.On("Init", ctx, eventID, ticketTypeID, total)}
}

func (_c *MockSeatCounter_Init_Call) Run(run func(ctx context.Context, eventID string, ticketTypeID string, total int)) *MockSeatCounter_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSeatCounter_Init_Call) Return(err error) *MockSeatCounter_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeatCounter_Init_Call) RunAndReturn(run func(ctx context.Context, eventID string, ticketTypeID string, total int) error) *MockSeatCounter_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockSeatCounter
func (_mock *MockSeatCounter) Release(ctx context.Context, eventID string, ticketTypeID string, qty int) error {
	ret := _mock.Called(ctx, eventID, ticketTypeID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, eventID, ticketTypeID, qty)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeatCounter_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockSeatCounter_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - ticketTypeID string
//   - qty int
func (_e *MockSeatCounter_Expecter) Release(ctx any, eventID any, ticketTypeID any, qty any) *MockSeatCounter_Release_Call {
	return &MockSeatCounter_Release_Call{Call: _e.mock.On("Release", ctx, eventID, ticketTypeID, qty)}
}

func (_c *MockSeatCounter_Release_Call) Run(run func(ctx context.Context, eventID string, ticketTypeID string, qty int)) *MockSeatCounter_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSeatCounter_Release_Call) Return(err error) *MockSeatCounter_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeatCounter_Release_Call) RunAndReturn(run func(ctx context.Context, eventID string, ticketTypeID string, qty int) error) *MockSeatCounter_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type MockSeatCounter
func (_mock *MockSeatCounter) Reserve(ctx context.Context, eventID string, ticketTypeID string, qty int) error {
	ret := _mock.Called(ctx, eventID, ticketTypeID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, eventID, ticketTypeID, qty)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeatCounter_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockSeatCounter_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - ticketTypeID string
//   - qty int
func (_e *MockSeatCounter_Expecter) Reserve(ctx any, eventID any, ticketTypeID any, qty any) *MockSeatCounter_Reserve_Call {
	return &MockSeatCounter_Reserve_Call{Call: _e.mock.On("Reserve", ctx, eventID, ticketTypeID, qty)}
}

func (_c *MockSeatCounter_Reserve_Call) Run(run func(ctx context.Context, eventID string, ticketTypeID string, qty int)) *MockSeatCounter_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSeatCounter_Reserve_Call) Return(err error) *MockSeatCounter_Reserve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeatCounter_Reserve_Call) RunAndReturn(run func(ctx context.Context, eventID string, ticketTypeID string, qty int) error) *MockSeatCounter_Reserve_Call {
	_c.Call.Return(run)
	return _c
}
