// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventStatusRepository creates a new instance of MockEventStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventStatusRepository {
	mock := &MockEventStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventStatusRepository is an autogenerated mock type for the EventStatusRepository type
type MockEventStatusRepository struct {
	mock.Mock
}

type MockEventStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventStatusRepository) EXPECT() *MockEventStatusRepository_Expecter {
	return &MockEventStatusRepository_Expecter{mock: &_m.Mock}
}

// IsPublished provides a mock function for the type MockEventStatusRepository
func (_mock *MockEventStatusRepository) IsPublished(ctx context.Context, eventID string) (bool, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsPublished")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventStatusRepository_IsPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPublished'
type MockEventStatusRepository_IsPublished_Call struct {
	*mock.Call
}

// IsPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockEventStatusRepository_Expecter) IsPublished(ctx any, eventID any) *MockEventStatusRepository_IsPublished_Call {
	return &MockEventStatusRepository_IsPublished_Call{Call: _e.mock.On("IsPublished", ctx, eventID)}
}

func (_c *MockEventStatusRepository_IsPublished_Call) Run(run func(ctx context.Context, eventID string)) *MockEventStatusRepository_IsPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStatusRepository_IsPublished_Call) Return(b bool, err error) *MockEventStatusRepository_IsPublished_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockEventStatusRepository_IsPublished_Call) RunAndReturn(run func(ctx context.Context, eventID string) (bool, error)) *MockEventStatusRepository_IsPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockEventStatusRepository
func (_mock *MockEventStatusRepository) Upsert(ctx context.Context, eventID string, status string) error {
	ret := _mock.Called(ctx, eventID, status)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, eventID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventStatusRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockEventStatusRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - status string
func (_e *MockEventStatusRepository_Expecter) Upsert(ctx any, eventID any, status any) *MockEventStatusRepository_Upsert_Call {
	return &MockEventStatusRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, eventID, status)}
}

func (_c *MockEventStatusRepository_Upsert_Call) Run(run func(ctx context.Context, eventID string, status string)) *MockEventStatusRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventStatusRepository_Upsert_Call) Return(err error) *MockEventStatusRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventStatusRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, eventID string, status string) error) *MockEventStatusRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
