// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nedo/TicketSaas/internal/inventory/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingRepository is an autogenerated mock type for the BookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// CancelByEventID provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) CancelByEventID(ctx context.Context, eventID string) error {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for CancelByEventID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingRepository_CancelByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelByEventID'
type MockBookingRepository_CancelByEventID_Call struct {
	*mock.Call
}

// CancelByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockBookingRepository_Expecter) CancelByEventID(ctx any, eventID any) *MockBookingRepository_CancelByEventID_Call {
	return &MockBookingRepository_CancelByEventID_Call{Call: _e.mock.On("CancelByEventID", ctx, eventID)}
}

func (_c *MockBookingRepository_CancelByEventID_Call) Run(run func(ctx context.Context, eventID string)) *MockBookingRepository_CancelByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_CancelByEventID_Call) Return(err error) *MockBookingRepository_CancelByEventID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingRepository_CancelByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID string) error) *MockBookingRepository_CancelByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) Create(ctx context.Context, booking *domain.Booking) error {
	ret := _mock.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Booking) error); ok {
		r0 = returnFunc(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - booking *domain.Booking
func (_e *MockBookingRepository_Expecter) Create(ctx any, booking any) *MockBookingRepository_Create_Call {
	return &MockBookingRepository_Create_Call{Call: _e.mock.On("Create", ctx, booking)}
}

func (_c *MockBookingRepository_Create_Call) Run(run func(ctx context.Context, booking *domain.Booking)) *MockBookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Booking
		if args[1] != nil {
			arg1 = args[1].(*domain.Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_Create_Call) Return(err error) *MockBookingRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingRepository_Create_Call) RunAndReturn(run func(ctx context.Context, booking *domain.Booking) error) *MockBookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) FindByID(ctx context.Context, id string) (*domain.Booking, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Booking, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Booking); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBookingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookingRepository_Expecter) FindByID(ctx any, id any) *MockBookingRepository_FindByID_Call {
	return &MockBookingRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBookingRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockBookingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_FindByID_Call) Return(booking *domain.Booking, err error) *MockBookingRepository_FindByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Booking, error)) *MockBookingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByEventID provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) ListByEventID(ctx context.Context, eventID string) ([]domain.Booking, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ListByEventID")
	}

	var r0 []domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Booking, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Booking); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_ListByEventID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByEventID'
type MockBookingRepository_ListByEventID_Call struct {
	*mock.Call
}

// ListByEventID is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockBookingRepository_Expecter) ListByEventID(ctx any, eventID any) *MockBookingRepository_ListByEventID_Call {
	return &MockBookingRepository_ListByEventID_Call{Call: _e.mock.On("ListByEventID", ctx, eventID)}
}

func (_c *MockBookingRepository_ListByEventID_Call) Run(run func(ctx context.Context, eventID string)) *MockBookingRepository_ListByEventID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_ListByEventID_Call) Return(bookings []domain.Booking, err error) *MockBookingRepository_ListByEventID_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingRepository_ListByEventID_Call) RunAndReturn(run func(ctx context.Context, eventID string) ([]domain.Booking, error)) *MockBookingRepository_ListByEventID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) ListByUser(ctx context.Context, userID string) ([]domain.Booking, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Booking, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Booking); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockBookingRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBookingRepository_Expecter) ListByUser(ctx any, userID any) *MockBookingRepository_ListByUser_Call {
	return &MockBookingRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockBookingRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockBookingRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_ListByUser_Call) Return(bookings []domain.Booking, err error) *MockBookingRepository_ListByUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.Booking, error)) *MockBookingRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) UpdateStatus(ctx context.Context, bookingID string, status string) error {
	ret := _mock.Called(ctx, bookingID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bookingID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockBookingRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
//   - status string
func (_e *MockBookingRepository_Expecter) UpdateStatus(ctx any, bookingID any, status any) *MockBookingRepository_UpdateStatus_Call {
	return &MockBookingRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, bookingID, status)}
}

func (_c *MockBookingRepository_UpdateStatus_Call) Run(run func(ctx context.Context, bookingID string, status string)) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingRepository_UpdateStatus_Call) Return(err error) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, bookingID string, status string) error) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
