// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReservationCache creates a new instance of MockReservationCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationCache {
	mock := &MockReservationCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReservationCache is an autogenerated mock type for the ReservationCache type
type MockReservationCache struct {
	mock.Mock
}

type MockReservationCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationCache) EXPECT() *MockReservationCache_Expecter {
	return &MockReservationCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockReservationCache
func (_mock *MockReservationCache) Delete(ctx context.Context, bookingID string) error {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReservationCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockReservationCache_Expecter) Delete(ctx any, bookingID any) *MockReservationCache_Delete_Call {
	return &MockReservationCache_Delete_Call{Call: _e.mock.On("Delete", ctx, bookingID)}
}

func (_c *MockReservationCache_Delete_Call) Run(run func(ctx context.Context, bookingID string)) *MockReservationCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationCache_Delete_Call) Return(err error) *MockReservationCache_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationCache_Delete_Call) RunAndReturn(run func(ctx context.Context, bookingID string) error) *MockReservationCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockReservationCache
func (_mock *MockReservationCache) Save(ctx context.Context, bookingID string, ttlSeconds int) error {
	ret := _mock.Called(ctx, bookingID, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, bookingID, ttlSeconds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationCache_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockReservationCache_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
//   - ttlSeconds int
func (_e *MockReservationCache_Expecter) Save(ctx any, bookingID any, ttlSeconds any) *MockReservationCache_Save_Call {
	return &MockReservationCache_Save_Call{Call: _e.mock.On("Save", ctx, bookingID, ttlSeconds)}
}

func (_c *MockReservationCache_Save_Call) Run(run func(ctx context.Context, bookingID string, ttlSeconds int)) *MockReservationCache_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservationCache_Save_Call) Return(err error) *MockReservationCache_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationCache_Save_Call) RunAndReturn(run func(ctx context.Context, bookingID string, ttlSeconds int) error) *MockReservationCache_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeExpiry provides a mock function for the type MockReservationCache
func (_mock *MockReservationCache) SubscribeExpiry(ctx context.Context) (<-chan string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeExpiry")
	}

	var r0 <-chan string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationCache_SubscribeExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeExpiry'
type MockReservationCache_SubscribeExpiry_Call struct {
	*mock.Call
}

// SubscribeExpiry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationCache_Expecter) SubscribeExpiry(ctx any) *MockReservationCache_SubscribeExpiry_Call {
	return &MockReservationCache_SubscribeExpiry_Call{Call: _e.mock.On("SubscribeExpiry", ctx)}
}

func (_c *MockReservationCache_SubscribeExpiry_Call) Run(run func(ctx context.Context)) *MockReservationCache_SubscribeExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservationCache_SubscribeExpiry_Call) Return(stringCh <-chan string, err error) *MockReservationCache_SubscribeExpiry_Call {
	_c.Call.Return(stringCh, err)
	return _c
}

func (_c *MockReservationCache_SubscribeExpiry_Call) RunAndReturn(run func(ctx context.Context) (<-chan string, error)) *MockReservationCache_SubscribeExpiry_Call {
	_c.Call.Return(run)
	return _c
}
