// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nedo/TicketSaas/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) Create(ctx context.Context, token *domain.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx any, token any) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*domain.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(err error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *domain.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByHash provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) DeleteByHash(ctx context.Context, hash string) error {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_DeleteByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByHash'
type MockRefreshTokenRepository_DeleteByHash_Call struct {
	*mock.Call
}

// DeleteByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRefreshTokenRepository_Expecter) DeleteByHash(ctx any, hash any) *MockRefreshTokenRepository_DeleteByHash_Call {
	return &MockRefreshTokenRepository_DeleteByHash_Call{Call: _e.mock.On("DeleteByHash", ctx, hash)}
}

func (_c *MockRefreshTokenRepository_DeleteByHash_Call) Run(run func(ctx context.Context, hash string)) *MockRefreshTokenRepository_DeleteByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByHash_Call) Return(err error) *MockRefreshTokenRepository_DeleteByHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) error) *MockRefreshTokenRepository_DeleteByHash_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) DeleteByUserID(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockRefreshTokenRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRefreshTokenRepository_Expecter) DeleteByUserID(ctx any, userID any) *MockRefreshTokenRepository_DeleteByUserID_Call {
	return &MockRefreshTokenRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByUserID_Call) Return(err error) *MockRefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockRefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) FindByHash(ctx context.Context, hash string) (*domain.RefreshToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockRefreshTokenRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRefreshTokenRepository_Expecter) FindByHash(ctx any, hash any) *MockRefreshTokenRepository_FindByHash_Call {
	return &MockRefreshTokenRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, hash)}
}

func (_c *MockRefreshTokenRepository_FindByHash_Call) Run(run func(ctx context.Context, hash string)) *MockRefreshTokenRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindByHash_Call) Return(refreshToken *domain.RefreshToken, err error) *MockRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepository_FindByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}
