// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	domain0 "github.com/nedo/TicketSaas/internal/auth/domain"
	"github.com/nedo/TicketSaas/internal/shared/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateAccessToken(userID string, email string, role domain.Role) (string, time.Duration, error) {
	ret := _mock.Called(userID, email, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 time.Duration
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, domain.Role) (string, time.Duration, error)); ok {
		return returnFunc(userID, email, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, domain.Role) string); ok {
		r0 = returnFunc(userID, email, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, domain.Role) time.Duration); ok {
		r1 = returnFunc(userID, email, role)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, domain.Role) error); ok {
		r2 = returnFunc(userID, email, role)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID string
//   - email string
//   - role domain.Role
func (_e *MockTokenService_Expecter) GenerateAccessToken(userID any, email any, role any) *MockTokenService_GenerateAccessToken_Call {
	return &MockTokenService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, email, role)}
}

func (_c *MockTokenService_GenerateAccessToken_Call) Run(run func(userID string, email string, role domain.Role)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Role
		if args[2] != nil {
			arg2 = args[2].(domain.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) Return(s string, duration time.Duration, err error) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(s, duration, err)
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) RunAndReturn(run func(userID string, email string, role domain.Role) (string, time.Duration, error)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateRefreshToken() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenService_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) GenerateRefreshToken() *MockTokenService_GenerateRefreshToken_Call {
	return &MockTokenService_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken")}
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Run(run func()) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Return(s string, err error) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) RunAndReturn(run func() (string, error)) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) HashRefreshToken(token string) string {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for HashRefreshToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenService_HashRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashRefreshToken'
type MockTokenService_HashRefreshToken_Call struct {
	*mock.Call
}

// HashRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) HashRefreshToken(token any) *MockTokenService_HashRefreshToken_Call {
	return &MockTokenService_HashRefreshToken_Call{Call: _e.mock.On("HashRefreshToken", token)}
}

func (_c *MockTokenService_HashRefreshToken_Call) Run(run func(token string)) *MockTokenService_HashRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_HashRefreshToken_Call) Return(s string) *MockTokenService_HashRefreshToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenService_HashRefreshToken_Call) RunAndReturn(run func(token string) string) *MockTokenService_HashRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAccessToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) VerifyAccessToken(tokenString string) (*domain0.Claims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccessToken")
	}

	var r0 *domain0.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain0.Claims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain0.Claims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_VerifyAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccessToken'
type MockTokenService_VerifyAccessToken_Call struct {
	*mock.Call
}

// VerifyAccessToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) VerifyAccessToken(tokenString any) *MockTokenService_VerifyAccessToken_Call {
	return &MockTokenService_VerifyAccessToken_Call{Call: _e.mock.On("VerifyAccessToken", tokenString)}
}

func (_c *MockTokenService_VerifyAccessToken_Call) Run(run func(tokenString string)) *MockTokenService_VerifyAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_VerifyAccessToken_Call) Return(claims *domain0.Claims, err error) *MockTokenService_VerifyAccessToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockTokenService_VerifyAccessToken_Call) RunAndReturn(run func(tokenString string) (*domain0.Claims, error)) *MockTokenService_VerifyAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
