// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nedo/TicketSaas/internal/payment/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Create(ctx context.Context, txn *domain.Transaction) error {
	ret := _mock.Called(ctx, txn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = returnFunc(ctx, txn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - txn *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx any, txn any) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, txn)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, txn *domain.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(*domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(err error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, txn *domain.Transaction) error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBookingID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) FindByBookingID(ctx context.Context, bookingID string) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBookingID")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Transaction); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_FindByBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBookingID'
type MockTransactionRepository_FindByBookingID_Call struct {
	*mock.Call
}

// FindByBookingID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockTransactionRepository_Expecter) FindByBookingID(ctx any, bookingID any) *MockTransactionRepository_FindByBookingID_Call {
	return &MockTransactionRepository_FindByBookingID_Call{Call: _e.mock.On("FindByBookingID", ctx, bookingID)}
}

func (_c *MockTransactionRepository_FindByBookingID_Call) Run(run func(ctx context.Context, bookingID string)) *MockTransactionRepository_FindByBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_FindByBookingID_Call) Return(transaction *domain.Transaction, err error) *MockTransactionRepository_FindByBookingID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_FindByBookingID_Call) RunAndReturn(run func(ctx context.Context, bookingID string) (*domain.Transaction, error)) *MockTransactionRepository_FindByBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) FindByID(ctx context.Context, id string) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTransactionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionRepository_Expecter) FindByID(ctx any, id any) *MockTransactionRepository_FindByID_Call {
	return &MockTransactionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTransactionRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) Return(transaction *domain.Transaction, err error) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Transaction, error)) *MockTransactionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) ListByUser(ctx context.Context, userID string) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Transaction); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockTransactionRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTransactionRepository_Expecter) ListByUser(ctx any, userID any) *MockTransactionRepository_ListByUser_Call {
	return &MockTransactionRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockTransactionRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTransactionRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_ListByUser_Call) Return(transactions []domain.Transaction, err error) *MockTransactionRepository_ListByUser_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockTransactionRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.Transaction, error)) *MockTransactionRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) UpdateStatus(ctx context.Context, id string, status string, providerRef string) error {
	ret := _mock.Called(ctx, id, status, providerRef)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, status, providerRef)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTransactionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
//   - providerRef string
func (_e *MockTransactionRepository_Expecter) UpdateStatus(ctx any, id any, status any, providerRef any) *MockTransactionRepository_UpdateStatus_Call {
	return &MockTransactionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, providerRef)}
}

func (_c *MockTransactionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status string, providerRef string)) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_UpdateStatus_Call) Return(err error) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status string, providerRef string) error) *MockTransactionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
