// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentProcessor creates a new instance of MockPaymentProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentProcessor {
	mock := &MockPaymentProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentProcessor is an autogenerated mock type for the PaymentProcessor type
type MockPaymentProcessor struct {
	mock.Mock
}

type MockPaymentProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentProcessor) EXPECT() *MockPaymentProcessor_Expecter {
	return &MockPaymentProcessor_Expecter{mock: &_m.Mock}
}

// Charge provides a mock function for the type MockPaymentProcessor
func (_mock *MockPaymentProcessor) Charge(ctx context.Context, txnID string, amountCents int, currency string) (string, error) {
	ret := _mock.Called(ctx, txnID, amountCents, currency)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) (string, error)); ok {
		return returnFunc(ctx, txnID, amountCents, currency)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) string); ok {
		r0 = returnFunc(ctx, txnID, amountCents, currency)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = returnFunc(ctx, txnID, amountCents, currency)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentProcessor_Charge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Charge'
type MockPaymentProcessor_Charge_Call struct {
	*mock.Call
}

// Charge is a helper method to define mock.On call
//   - ctx context.Context
//   - txnID string
//   - amountCents int
//   - currency string
func (_e *MockPaymentProcessor_Expecter) Charge(ctx any, txnID any, amountCents any, currency any) *MockPaymentProcessor_Charge_Call {
	return &MockPaymentProcessor_Charge_Call{Call: _e.mock.On("Charge", ctx, txnID, amountCents, currency)}
}

func (_c *MockPaymentProcessor_Charge_Call) Run(run func(ctx context.Context, txnID string, amountCents int, currency string)) *MockPaymentProcessor_Charge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentProcessor_Charge_Call) Return(s string, err error) *MockPaymentProcessor_Charge_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPaymentProcessor_Charge_Call) RunAndReturn(run func(ctx context.Context, txnID string, amountCents int, currency string) (string, error)) *MockPaymentProcessor_Charge_Call {
	_c.Call.Return(run)
	return _c
}
