// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizerConsumer creates a new instance of MockOrganizerConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizerConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizerConsumer {
	mock := &MockOrganizerConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizerConsumer is an autogenerated mock type for the OrganizerConsumer type
type MockOrganizerConsumer struct {
	mock.Mock
}

type MockOrganizerConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizerConsumer) EXPECT() *MockOrganizerConsumer_Expecter {
	return &MockOrganizerConsumer_Expecter{mock: &_m.Mock}
}

// OnOrganizerCreated provides a mock function for the type MockOrganizerConsumer
func (_mock *MockOrganizerConsumer) OnOrganizerCreated(ctx context.Context, fn func(context.Context, string, string, string, string, string) error) {
	_mock.Called(ctx, fn)
	return
}

// MockOrganizerConsumer_OnOrganizerCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnOrganizerCreated'
type MockOrganizerConsumer_OnOrganizerCreated_Call struct {
	*mock.Call
}

// OnOrganizerCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context, string, string, string, string, string) error
func (_e *MockOrganizerConsumer_Expecter) OnOrganizerCreated(ctx any, fn any) *MockOrganizerConsumer_OnOrganizerCreated_Call {
	return &MockOrganizerConsumer_OnOrganizerCreated_Call{Call: _e.mock.On("OnOrganizerCreated", ctx, fn)}
}

func (_c *MockOrganizerConsumer_OnOrganizerCreated_Call) Run(run func(ctx context.Context, fn func(context.Context, string, string, string, string, string) error)) *MockOrganizerConsumer_OnOrganizerCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context, string, string, string, string, string) error
		if args[1] != nil {
			arg1 = args[1].(func(context.Context, string, string, string, string, string) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizerConsumer_OnOrganizerCreated_Call) Return() *MockOrganizerConsumer_OnOrganizerCreated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrganizerConsumer_OnOrganizerCreated_Call) RunAndReturn(run func(ctx context.Context, fn func(context.Context, string, string, string, string, string) error)) *MockOrganizerConsumer_OnOrganizerCreated_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockOrganizerConsumer
func (_mock *MockOrganizerConsumer) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizerConsumer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockOrganizerConsumer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrganizerConsumer_Expecter) Start(ctx any) *MockOrganizerConsumer_Start_Call {
	return &MockOrganizerConsumer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockOrganizerConsumer_Start_Call) Run(run func(ctx context.Context)) *MockOrganizerConsumer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrganizerConsumer_Start_Call) Return(err error) *MockOrganizerConsumer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizerConsumer_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockOrganizerConsumer_Start_Call {
	_c.Call.Return(run)
	return _c
}
