// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nedo/TicketSaas/internal/event/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// CreateEvent provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) CreateEvent(ctx context.Context, event *domain.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockEventRepository_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *domain.Event
func (_e *MockEventRepository_Expecter) CreateEvent(ctx any, event any) *MockEventRepository_CreateEvent_Call {
	return &MockEventRepository_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, event)}
}

func (_c *MockEventRepository_CreateEvent_Call) Run(run func(ctx context.Context, event *domain.Event)) *MockEventRepository_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Event
		if args[1] != nil {
			arg1 = args[1].(*domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_CreateEvent_Call) Return(err error) *MockEventRepository_CreateEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_CreateEvent_Call) RunAndReturn(run func(ctx context.Context, event *domain.Event) error) *MockEventRepository_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganizer provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) CreateOrganizer(ctx context.Context, org *domain.Organizer) error {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Organizer) error); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_CreateOrganizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizer'
type MockEventRepository_CreateOrganizer_Call struct {
	*mock.Call
}

// CreateOrganizer is a helper method to define mock.On call
//   - ctx context.Context
//   - org *domain.Organizer
func (_e *MockEventRepository_Expecter) CreateOrganizer(ctx any, org any) *MockEventRepository_CreateOrganizer_Call {
	return &MockEventRepository_CreateOrganizer_Call{Call: _e.mock.On("CreateOrganizer", ctx, org)}
}

func (_c *MockEventRepository_CreateOrganizer_Call) Run(run func(ctx context.Context, org *domain.Organizer)) *MockEventRepository_CreateOrganizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Organizer
		if args[1] != nil {
			arg1 = args[1].(*domain.Organizer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_CreateOrganizer_Call) Return(err error) *MockEventRepository_CreateOrganizer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_CreateOrganizer_Call) RunAndReturn(run func(ctx context.Context, org *domain.Organizer) error) *MockEventRepository_CreateOrganizer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTicketTypes provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) CreateTicketTypes(ctx context.Context, types []domain.TicketType) error {
	ret := _mock.Called(ctx, types)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicketTypes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.TicketType) error); ok {
		r0 = returnFunc(ctx, types)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_CreateTicketTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicketTypes'
type MockEventRepository_CreateTicketTypes_Call struct {
	*mock.Call
}

// CreateTicketTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - types []domain.TicketType
func (_e *MockEventRepository_Expecter) CreateTicketTypes(ctx any, types any) *MockEventRepository_CreateTicketTypes_Call {
	return &MockEventRepository_CreateTicketTypes_Call{Call: _e.mock.On("CreateTicketTypes", ctx, types)}
}

func (_c *MockEventRepository_CreateTicketTypes_Call) Run(run func(ctx context.Context, types []domain.TicketType)) *MockEventRepository_CreateTicketTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.TicketType
		if args[1] != nil {
			arg1 = args[1].([]domain.TicketType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_CreateTicketTypes_Call) Return(err error) *MockEventRepository_CreateTicketTypes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_CreateTicketTypes_Call) RunAndReturn(run func(ctx context.Context, types []domain.TicketType) error) *MockEventRepository_CreateTicketTypes_Call {
	_c.Call.Return(run)
	return _c
}

// FindEventByID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) FindEventByID(ctx context.Context, id string) (*domain.Event, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindEventByID")
	}

	var r0 *domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Event, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Event); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_FindEventByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEventByID'
type MockEventRepository_FindEventByID_Call struct {
	*mock.Call
}

// FindEventByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEventRepository_Expecter) FindEventByID(ctx any, id any) *MockEventRepository_FindEventByID_Call {
	return &MockEventRepository_FindEventByID_Call{Call: _e.mock.On("FindEventByID", ctx, id)}
}

func (_c *MockEventRepository_FindEventByID_Call) Run(run func(ctx context.Context, id string)) *MockEventRepository_FindEventByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_FindEventByID_Call) Return(event *domain.Event, err error) *MockEventRepository_FindEventByID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_FindEventByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Event, error)) *MockEventRepository_FindEventByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrganizerByUserID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) FindOrganizerByUserID(ctx context.Context, userID string) (*domain.Organizer, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrganizerByUserID")
	}

	var r0 *domain.Organizer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Organizer, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Organizer); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organizer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_FindOrganizerByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrganizerByUserID'
type MockEventRepository_FindOrganizerByUserID_Call struct {
	*mock.Call
}

// FindOrganizerByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockEventRepository_Expecter) FindOrganizerByUserID(ctx any, userID any) *MockEventRepository_FindOrganizerByUserID_Call {
	return &MockEventRepository_FindOrganizerByUserID_Call{Call: _e.mock.On("FindOrganizerByUserID", ctx, userID)}
}

func (_c *MockEventRepository_FindOrganizerByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockEventRepository_FindOrganizerByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_FindOrganizerByUserID_Call) Return(organizer *domain.Organizer, err error) *MockEventRepository_FindOrganizerByUserID_Call {
	_c.Call.Return(organizer, err)
	return _c
}

func (_c *MockEventRepository_FindOrganizerByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.Organizer, error)) *MockEventRepository_FindOrganizerByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrganizer provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ListByOrganizer(ctx context.Context, organizerID string) ([]domain.Event, error) {
	ret := _mock.Called(ctx, organizerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrganizer")
	}

	var r0 []domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Event, error)); ok {
		return returnFunc(ctx, organizerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Event); ok {
		r0 = returnFunc(ctx, organizerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, organizerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_ListByOrganizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrganizer'
type MockEventRepository_ListByOrganizer_Call struct {
	*mock.Call
}

// ListByOrganizer is a helper method to define mock.On call
//   - ctx context.Context
//   - organizerID string
func (_e *MockEventRepository_Expecter) ListByOrganizer(ctx any, organizerID any) *MockEventRepository_ListByOrganizer_Call {
	return &MockEventRepository_ListByOrganizer_Call{Call: _e.mock.On("ListByOrganizer", ctx, organizerID)}
}

func (_c *MockEventRepository_ListByOrganizer_Call) Run(run func(ctx context.Context, organizerID string)) *MockEventRepository_ListByOrganizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_ListByOrganizer_Call) Return(events []domain.Event, err error) *MockEventRepository_ListByOrganizer_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventRepository_ListByOrganizer_Call) RunAndReturn(run func(ctx context.Context, organizerID string) ([]domain.Event, error)) *MockEventRepository_ListByOrganizer_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ListPending(ctx context.Context, limit int, offset int) ([]domain.Event, int, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []domain.Event
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Event, int, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []domain.Event); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventRepository_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type MockEventRepository_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockEventRepository_Expecter) ListPending(ctx any, limit any, offset any) *MockEventRepository_ListPending_Call {
	return &MockEventRepository_ListPending_Call{Call: _e.mock.On("ListPending", ctx, limit, offset)}
}

func (_c *MockEventRepository_ListPending_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockEventRepository_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_ListPending_Call) Return(events []domain.Event, n int, err error) *MockEventRepository_ListPending_Call {
	_c.Call.Return(events, n, err)
	return _c
}

func (_c *MockEventRepository_ListPending_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]domain.Event, int, error)) *MockEventRepository_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublished provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ListPublished(ctx context.Context, limit int, offset int) ([]domain.Event, int, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPublished")
	}

	var r0 []domain.Event
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Event, int, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []domain.Event); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventRepository_ListPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublished'
type MockEventRepository_ListPublished_Call struct {
	*mock.Call
}

// ListPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockEventRepository_Expecter) ListPublished(ctx any, limit any, offset any) *MockEventRepository_ListPublished_Call {
	return &MockEventRepository_ListPublished_Call{Call: _e.mock.On("ListPublished", ctx, limit, offset)}
}

func (_c *MockEventRepository_ListPublished_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockEventRepository_ListPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_ListPublished_Call) Return(events []domain.Event, n int, err error) *MockEventRepository_ListPublished_Call {
	_c.Call.Return(events, n, err)
	return _c
}

func (_c *MockEventRepository_ListPublished_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]domain.Event, int, error)) *MockEventRepository_ListPublished_Call {
	_c.Call.Return(run)
	return _c
}

// ListTicketTypesByEvent provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ListTicketTypesByEvent(ctx context.Context, eventID string) ([]domain.TicketType, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ListTicketTypesByEvent")
	}

	var r0 []domain.TicketType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.TicketType, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.TicketType); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TicketType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_ListTicketTypesByEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTicketTypesByEvent'
type MockEventRepository_ListTicketTypesByEvent_Call struct {
	*mock.Call
}

// ListTicketTypesByEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockEventRepository_Expecter) ListTicketTypesByEvent(ctx any, eventID any) *MockEventRepository_ListTicketTypesByEvent_Call {
	return &MockEventRepository_ListTicketTypesByEvent_Call{Call: _e.mock.On("ListTicketTypesByEvent", ctx, eventID)}
}

func (_c *MockEventRepository_ListTicketTypesByEvent_Call) Run(run func(ctx context.Context, eventID string)) *MockEventRepository_ListTicketTypesByEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_ListTicketTypesByEvent_Call) Return(ticketTypes []domain.TicketType, err error) *MockEventRepository_ListTicketTypesByEvent_Call {
	_c.Call.Return(ticketTypes, err)
	return _c
}

func (_c *MockEventRepository_ListTicketTypesByEvent_Call) RunAndReturn(run func(ctx context.Context, eventID string) ([]domain.TicketType, error)) *MockEventRepository_ListTicketTypesByEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) UpdateEvent(ctx context.Context, event *domain.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockEventRepository_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *domain.Event
func (_e *MockEventRepository_Expecter) UpdateEvent(ctx any, event any) *MockEventRepository_UpdateEvent_Call {
	return &MockEventRepository_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", ctx, event)}
}

func (_c *MockEventRepository_UpdateEvent_Call) Run(run func(ctx context.Context, event *domain.Event)) *MockEventRepository_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Event
		if args[1] != nil {
			arg1 = args[1].(*domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_UpdateEvent_Call) Return(err error) *MockEventRepository_UpdateEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_UpdateEvent_Call) RunAndReturn(run func(ctx context.Context, event *domain.Event) error) *MockEventRepository_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}
