// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSeatReader creates a new instance of MockSeatReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeatReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeatReader {
	mock := &MockSeatReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSeatReader is an autogenerated mock type for the SeatReader type
type MockSeatReader struct {
	mock.Mock
}

type MockSeatReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeatReader) EXPECT() *MockSeatReader_Expecter {
	return &MockSeatReader_Expecter{mock: &_m.Mock}
}

// Available provides a mock function for the type MockSeatReader
func (_mock *MockSeatReader) Available(ctx context.Context, eventID string, ticketTypeID string) int {
	ret := _mock.Called(ctx, eventID, ticketTypeID)

	if len(ret) == 0 {
		panic("no return value specified for Available")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = returnFunc(ctx, eventID, ticketTypeID)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockSeatReader_Available_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Available'
type MockSeatReader_Available_Call struct {
	*mock.Call
}

// Available is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - ticketTypeID string
func (_e *MockSeatReader_Expecter) Available(ctx any, eventID any, ticketTypeID any) *MockSeatReader_Available_Call {
	return &MockSeatReader_Available_Call{Call: _e.mock.On("Available", ctx, eventID, ticketTypeID)}
}

func (_c *MockSeatReader_Available_Call) Run(run func(ctx context.Context, eventID string, ticketTypeID string)) *MockSeatReader_Available_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSeatReader_Available_Call) Return(n int) *MockSeatReader_Available_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockSeatReader_Available_Call) RunAndReturn(run func(ctx context.Context, eventID string, ticketTypeID string) int) *MockSeatReader_Available_Call {
	_c.Call.Return(run)
	return _c
}
